### ISSUE TITLE
Results Tab (TMDL-Widget) Plats - 6.43.2

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#51]
A Plats tab needs to be created under the vertical "Other" tab for all Strategies.(see screen shot)
![plats tab](https://cloud.githubusercontent.com/assets/4129185/3316485/229d9250-f703-11e3-807a-f732db31aab3.JPG)

The Other Tab should be visible for All Strategies (see highlighted area in screen shot)
![other tab](https://cloud.githubusercontent.com/assets/4129185/3316502/57014500-f703-11e3-8dc1-5f3448a0cbe5.JPG)

**Comment by ecomwu** [comment]
I've added Plats tab to both Assess and Site selection, committed the changes already. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed

**Comment by rmeitl** [comment]
Add the following fields to the Plats tab both in Assets and Site Selections:

Plat Reference: (PLAT_REFERENCES.PLAT_REFERENCE) - text, editable
Research Status: (PLAT_REFERENCES.RESEARCH_STATUS) - editable with drop down using D_Research_Status

A feature (asset or site selection) can have many plats.

To join to Assets to find plat reference records, use the following keys:
For LandUse Change Assets:
LUCHANGE_BMP.LUCHANGE_BMP_ID = PLAT_REFERENCES.TMDL_ASSOCIATED_ID

For Efficiency BMP Assets:
EFF_BMP.TMDL_EFF_BMP_ID = PLAT_REFERENCES.TMDL_ASSOCIATED_ID

For Stream Assets:
STREAM_RESTORATION.STREAM_REST_ID = PLAT_REFERENCES.TMDL_ASSOCIATED_ID

To join to Site Selections, use the following keys:

TREE_SITE_SELECTION.TREE_SITE_SELECTION_ID = PLAT_REFERENCES.TMDL_ASSOCIATED_ID

STREAM_SITE_SELECTION.STREAM_SITE_SEL_ID = PLAT_REFERENCES.TMDL_ASSOCIATED_ID

PVMNT_REM_SITE_SELECT.PAVEMENT_RMV_SEL_ID = PLAT_REFERENCES.TMDL_ASSOCIATED_ID

OTFLL_STAB_SITE_SELECT.OF_STAB_SITE_SEL_ID = PLAT_REFERENCES.TMDL_ASSOCIATED_ID

LUCHANGE_SITE_SELECITON.LUCHANGE_SITE_SELECT_ID = PLAT_REFERENCES.TMDL_ASSOCIATED_ID

OTHER_SITE_SELECTION.OTEHR_SITE_SELECT_ID = PLAT_REFERENCES.TMDL_ASSOCIATED_ID

EFF_BMP_RTRFT_SITE_SELECT.EFF_BMP_RETROFIT_SELECT_ID = PLAT_REFERENCES.TMDL_ASSOCIATED_ID

EFF_BMP_SITE_SELECTION.EFF_BMP_SELECT_ID = PLAT_REFERENCES.TMDL_ASSOCIATED_ID

Let me know if you have any questions.

**Comment by ecomwu** [comment]
I've made changes to those two field:
- Change field name "Plat ID" to "Plat Reference"
- Change Research Status from text input to dropdown by using D_Research _Status

**Comment by dhenry-KCI** [comment]
Maggie- The Plats don't seem to be displaying correctly. Bioswales within watershed 021307021130 have related Plats but no results are being displayed within the widget.

To recreate:
Strategies>Swales

12 Digit Watershed = 021307021130

Swlaes within this watershed have plats but no records are being displayed.

**Comment by ecomwu** [comment]
After changing the code, I still don't have data return for this selection.
@ehsan67  could you help me to look into that?

**Comment by ehsan67** [comment]
@ecomwu  Select Tree planting , then filter based on 12 digit watershed "021309061012" . Then find "030216UT" value in the first column . It has 2 plat references.

**Comment by ecomwu** [comment]
This issue is fixed after testing. Please test it in next release.

**Comment by ecomwu** [comment]
@ehsan67  Could you help me take a look at this issue? I thought it might be data issue. there is no data return.
To recreate:
 Strategies>Swales

12 Digit Watershed = 021307021130

Swlaes within this watershed have plats but no records are being displayed.

**Comment by ehsan67** [comment]
@ecomwu @dhenry-KCI  I don't see any Plat records for Swales in 021307021130 watershed area. Are you sure the data exist?
